---
title: "Taller 1"
author: 
- "Juan Sosa PhD" 
- "jcsosam@unal.edu.co"
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Suponga que si $\theta = i$, entonces $y$ tiene una distribución Normal con media $i$ y desviación estándar $\sigma$, para $i = 1,2$. Además, suponga que $\textsf{Pr}(\theta = 1) = \textsf{Pr}(\theta = 2) = 0.5$.

    a. Escriba una expresión general para la densidad marginal de $y$ y dibújela para $\sigma = 2$.
    b. Calcule $\textsf{Pr}(\theta = 1\mid y = 1)$ y $\textsf{Pr}(\theta = 2\mid y = 1)$ para $\sigma = 2$.

2. Suponga que la urna $C$ está llena de 60\% de balotas verdes y 40\% de balotas rojas, y que la urna $S$ está llena de 40\% de balotas verdes y 60\% de balotas rojas. Alguien lanza una moneda y selecciona una balota de la urna $C$ o la urna $S$ dependiendo de si la moneda cae cara o sello, respectivamente. Sea $x$ igual a 1 si la moneda cae cara y 0 si la moneda cae sello, y sea $y$ igual a 1 si la balota es verde y 0 si la balota es roja. 

    a. Calcule $\textsf{Var}(y)$, $\textsf{Var}(y\mid x = 0)$, $\textsf{Var}(y\mid x = 1)$. 			
    b. Considerando la varianza como una medida de la incertidumbre, explique por qué una de estas varianzas es mayor que las otras.

3. A continuación se presentan los antecedentes (supuestos y juicios de valor) $\mathcal{B}$ para este problema:
$B_1$: Por lo general, los estadísticos tienden a tener personalidades tímidas con más frecuencia que los economistas. Se cuantifica esta observación asumiendo que el 80\% de los estadísticos son tímidos, pero el porcentaje correspondiente entre los economistas es sólo del 15\%. $B_2$: A las conferencias sobre econometría asisten casi exclusivamente economistas y estadísticos, y la mayoría de los participantes son economistas. Se cuantifica esta observación asumiendo que el 90\% de los asistentes son economistas (y el resto estadísticos).

    a. Suponga que Usted (un físico, digamos) va a una conferencia de econometría y entabla una conversación con la primera persona que conoce (al azar) y descubre que esta persona es tímida. El objetivo de este problema es mostrar que la probabilidad (condicional) $p$ de que esté hablando con un estadístico, dados estos datos y los antecedentes, es de aproximadamente 37\%. Sea $St =$ "la persona es estadística", $E =$ ''la persona es economista" y $Sh =$ "la persona es tímida". Muestre que:
$$
\frac{ \textsf{Pr} ( St \mid Sh  ) }{ \textsf{Pr} ( E \mid Sh ) } =  \frac{ \textsf{Pr} ( St ) }{ \textsf{Pr} ( E ) } \cdot \frac{ \textsf{Pr} ( Sh \mid St ) }{ \textsf{Pr} ( Sh \mid E ) }\,.
$$	
    b. Muestre que la posibilidad relativa posterior $o$ a favor de $St$ sobre $E$ dados los datos, es $o = \frac{ 16 }{ 27 } \approx 0.593$.
    c. Muestre que la probabilidad pedida en este problema es $p = \frac{ o }{ 1 + o } = \frac{ 16 }{ 43 } \approx 0.372$.
    d. Alguien dice, "esa probabilidad no puede ser correcta: el 80\% de los estadísticos son tímidos, frente al 15\% de los economistas, por lo que su probabilidad de hablar con un estadístico debe ser superior al 50\%". Explique por qué esta línea de razonamiento es incorrecta y por qué $p$ debería ser menor del 50\%.
