---
title: "Taller # 3"
author: 
- Juan Sosa PhD
- Webpage https://sites.google.com/view/juansosa/ 
- YouTube https://www.youtube.com/c/JuanSosa1702 
- GitHub  https://github.com/jstats1702 
- Rpubs   https://rpubs.com/jstats1702
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. La siguiente tabla muestra el número de accidentes mortales por año asociados con aerolíneas en todo el mundo durante un período de diez años (Fuente: *Statistical Abstract of the United States*). Suponga que el número de accidentes mortales en cada año son condicionalmente independientes y siguen una distribución Poisson con parámetro $\theta$. Establezca una distribución previa para $\theta$ y determine la distribución posterior con base en los datos de 1976 a 1985. Bajo este modelo, calcule un intervalo predictivo al 95% para el número de accidentes fatales en 1986.


| Año  | Accidentes mortales |
|:----:|:-------------------:|
|	1976 | 24                  |
|	1977 | 25                  |
|	1978 | 31                  |
|	1979 | 31                  |
|	1980 | 22                  | 
|	1981 | 21                  | 
|	1982 | 26                  | 
|	1983 | 20                  | 
|	1984 | 16                  | 
|	1985 | 22                  |

2. Un laboratorio está estimando la tasa de *tumorigenesis* en dos cepas de ratones, A y B. Los ratones tipo A han sido bien estudiados e información de otros laboratorios sugiere que los ratones tipo A tienen conteos de tumores que siguen una distribución de Poisson con media $\theta_A = 12$. Se desconoce la tasa promedio de los tumores para los ratones tipo B, $\theta_B$, pero existe suficiente evidencia empírica para asegurar que los ratones tipo B están relacionados con los ratones tipo A. Los conteos de tumores observados para las dos cepas de ratones son
$\boldsymbol{y}_A = (12, 9, 12, 14, 13, 13, 15, 8, 15, 6)$ y $\boldsymbol{y}_B = (11, 11, 10, 9, 9, 8, 7, 10, 6, 8, 8, 9, 7)$.

a. Encuentre las distribuciones posteriores, las medias posteriores, las varianzas posteriores y los intervalos de credibilidad del 95\% para $\theta_A$ y $\theta_B$, asumiendo modelos Gamma-Poisson independientes para cada grupo, con distribuciones previas $\theta_A\sim\textsf{Gamma}(120,10)$ y $\theta_B\sim\textsf{Gamma}(12,1)$. ¿Por qué estas distribuciones previas son razonables?

b. Calcule y grafique la media posterior de $\theta_B$ bajo la distribución previa $\theta_B\sim \textsf{Gamma}(12m,m)$, para cada valor de $m\in\{1, 2,\ldots,50\}$. Describa qué tipo de información previa sobre $\theta_B$ sería necesaria para que la media posterior de $\theta_B$ sea cercana a la de $\theta_A$.

3. Muestre que bajo el modelo Gamma-Poison $y_i\mid\theta\stackrel{\text{iid}}{\sim}\textsf{Poisson}(y_i\mid\theta)$, para $i = 1,\ldots,n$, con $\theta \sim \textsf{Gamma}(a,b)$,
se tiene que la distribución predictiva posterior es Binomial Negativa con parámeros $a+s$ y $b+n$.

4. Considere el modelo Gamma-Poison $y_i\mid\theta\stackrel{\text{iid}}{\sim}\textsf{Poisson}(y_i\mid\theta)$, para $i = 1,\ldots,n$, con $\theta \sim \textsf{Gamma}(a,b)$, y la función de perdida cuadrática $L(\theta,\theta^*)=(\theta-\theta^*)^2$.

a. Muestre que el estimador que minimiza la perdida esperada posterior es de la forma $\hat\theta = a + b\,\bar{y}$, donde $a > 0$, $b \in (0, 1)$ y $\bar{y}=\frac{1}{n}\sum_{i=1}^n y_i$.
b. Calcule el riesgo frecuentista tanto de $\hat\theta$ como del estimador de máxima verosimilitud.
c. Calcule el riesgo Bayesiano de $\hat\theta$.
d. Suponga que un investigador quiere recolectar una muestra lo suficientemente grande para que el riesgo Bayesiano después del experimento sea la mitad del riesgo Bayesiano antes del experimento. Encuentre ese tamaño de muestra.

5. Considere el modelo Beta-Binomial $x\mid\theta\sim \textsf{Bin}(n,\theta)$ con $n$ conocido, y $\theta\sim \textsf{Beta}(\sqrt{n}/2,\sqrt{n}/2)$.

a. ¿Cuál es la distribución posterior?
b. ¿Cuál es el estimador que minimiza la perdida esperada posterior si la función de perdida es $L(\theta,\theta^*)=(\theta-\theta^*)^2$? Llame tal estimador $\hat{\theta}$ y muestre que el riesgo frecuentista correspondiente es constante.
c. Sea $\theta_0=x/n$. Encuentre el riesgo frecuentista de este estimador. Compare los riesgos de $\hat{\theta}$ y $\theta_0$, para $n=10,50,100$. ¿Qué se puede concluir?

6. Sea $x\sim \textsf{Bin}(n,\theta)$ con $n$ conocido, y $\theta \sim Beta(a,b)$. Considere la función de perdida $L(\theta,\theta^*)=(\theta-\theta^*)/(\theta(1-\theta))$. Encuentre el estimador que minimiza la perdida esperada posterior para esta función de perdida.

7. Sea $L(\theta,\theta^*) = \omega(\theta)(\theta - \theta^*)^2$ la función de perdida cuadrática ponderada, donde $\omega(\theta)$ es una función no negativa. Muestre que el estimador que minimiza la perdida esperada posterior tiene la forma
$$
\hat\theta=\frac{\textsf{E}(\omega(\theta)\,\theta\mid x)}{\textsf{E}(\omega(\theta)\mid x)}\,.
$$

